server:
  servlet:
    context-path: /ic

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/hr?userUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: 123
  thymeleaf:
    cache: false
mybatis:
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: ic.demo.entity